### ISSUE TITLE
Build fails because of undefined COMMON_PATH, fix to LOCAL_PATH?

### ISSUE THREAD

**Issue by fwiep** [TALUAtGitHub/android_device_samsung_gtaxl-common#1]
Hi,

Having followed the instructions to build LOS19.1 for the `gtaxlwifi` device, I encounter a "file-not-found" error:
 ```
FAILED: ninja: '/configs/cgroups.json', needed by 'out/target/product/gtaxlwifi/system/vendor/etc/cgroups.json', missing and no known rule to make it
```
After investigating the issue, I conclude that a recent commit to `common.mk` has introduced a reference to `COMMON_PATH`, which is not defined. Therefore, ninja cannot find the `cgroups.json` file and aborts the build.

Replacing the references to `LOCAL_PATH` seems to fix the issue; ninja now builds happily without any complaints.

https://github.com/TALUAtGitHub/android_device_samsung_gtaxl-common/blob/3cea3fe5ed5fc1c773027d9a8ecae3d7062c994a/common.mk#L108-L109

Was the reference to `COMMON_PATH` intentional, have I possibly broken something else down the line?

If not, should I create a pull request to alter these two lines?

Thanks and kind regards,
FWieP

**Comment by TALUAtGitHub** [comment]
Hi,
I've just fixed that problem up (edited the mistake out of the commit adding those files through a rebase + applying a commit for switching LOCAL_PATH -> COMMON_PATH entirely in some places also of course switching the definitions).

Just didn't build test after applying that first commit. Thanks for letting me know of the problem.
